# 基础配置
owner: NORMAL-EX
repo: upptime

# 要监控的网站
sites:
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://github.com

# 状态网站配置  
status-website:
  name: Status Page
  introTitle: "Status Page"
  introMessage: Monitoring our services
  navbar:
    - title: Status
      href: /
